<?php
/**  ______ _                 _               _ ___
 *  |  ____| |               | |             | |__ \
 *  | |__  | |_   ___      __| |__   ___  ___| |  ) |
 *  |  __| | | | | \ \ /\ / /| '_ \ / _ \/ _ \ | / /
 *  | |    | | |_| |\ V  V / | | | |  __/  __/ |/ /_
 *  |_|    |_|\__, | \_/\_/  |_| |_|\___|\___|_|____|
 *             __/ |
 *            |___/
 *
 * Flywheel2: the inertia php framework
 *
 * @category	Flywheel2
 * @package		other
 * @author		wakaba <wakabadou@gmail.com>
 * @copyright	2011- Wakabadou honpo (http://www.wakabadou.net/) / Project ICKX (http://www.ickx.jp/)
 * @license		http://opensource.org/licenses/MIT The MIT License MIT
 * @varsion		2.0.0
 */

namespace ickx\fw2\other\network;

/**
 * ドメインを纏めて扱うクラスです。
 *
 * @category	Flywheel2
 * @package		other
 * @author		wakaba <wakabadou@gmail.com>
 * @license		http://opensource.org/licenses/MIT The MIT License MIT
 * @varsion		2.0.0
 */
class DomainUtility {
	public static function topLevelDomainList () {
		return array(
				'com'				=> array('name' => 'com', 'entity' => '商用', 'idn' => true, 'dnssec' => true),
				'org'				=> array('name' => 'org', 'entity' => '団体', 'idn' => true, 'dnssec' => true),
				'net'				=> array('name' => 'net', 'entity' => 'ネットワークインフラ', 'idn' => true, 'dnssec' => true),
				'int'				=> array('name' => 'int', 'entity' => '国際機関', 'idn' => false, 'dnssec' => false),
				'edu'				=> array('name' => 'edu', 'entity' => 'アメリカ合衆国内の高等教育機関', 'idn' => false, 'dnssec' => true),
				'gov'				=> array('name' => 'gov', 'entity' => 'アメリカ合衆国連邦政府', 'idn' => false, 'dnssec' => true),
				'mil'				=> array('name' => 'mil', 'entity' => 'アメリカ合衆国の軍事機関', 'idn' => false, 'dnssec' => true),
				'arpa'				=> array('name' => 'arpa', 'entity' => 'Address and Routing Parameter Area', 'idn' => false, 'dnssec' => true),
				'ac'				=> array('name' => 'ac', 'entity' => 'アセンション島', 'idn' => true, 'dnssec' => true),
				'ad'				=> array('name' => 'ad', 'entity' => 'アンドラ', 'idn' => null, 'dnssec' => true),
				'ae'				=> array('name' => 'ae', 'entity' => 'アラブ首長国連邦', 'idn' => null, 'dnssec' => false),
				'af'				=> array('name' => 'af', 'entity' => 'アフガニスタン', 'idn' => null, 'dnssec' => true),
				'ag'				=> array('name' => 'ag', 'entity' => 'アンティグア・バーブーダ', 'idn' => null, 'dnssec' => true),
				'ai'				=> array('name' => 'ai', 'entity' => 'アンギラ', 'idn' => null, 'dnssec' => false),
				'al'				=> array('name' => 'al', 'entity' => 'アルバニア', 'idn' => null, 'dnssec' => false),
				'am'				=> array('name' => 'am', 'entity' => 'アルメニア', 'idn' => false, 'dnssec' => true),
				'an'				=> array('name' => 'an', 'entity' => 'オランダ領アンティル', 'idn' => null, 'dnssec' => false),
				'ao'				=> array('name' => 'ao', 'entity' => 'アンゴラ', 'idn' => null, 'dnssec' => false),
				'aq'				=> array('name' => 'aq', 'entity' => '南極', 'idn' => null, 'dnssec' => false),
				'ar'				=> array('name' => 'ar', 'entity' => 'アルゼンチン', 'idn' => true, 'dnssec' => true),
				'as'				=> array('name' => 'as', 'entity' => 'アメリカ領サモア', 'idn' => true, 'dnssec' => false),
				'at'				=> array('name' => 'at', 'entity' => 'オーストリア', 'idn' => null, 'dnssec' => true),
				'au'				=> array('name' => 'au', 'entity' => 'オーストラリア', 'idn' => null, 'dnssec' => true),
				'aw'				=> array('name' => 'aw', 'entity' => 'アルバ', 'idn' => null, 'dnssec' => true),
				'ax'				=> array('name' => 'ax', 'entity' => 'オーランド諸島', 'idn' => null, 'dnssec' => false),
				'az'				=> array('name' => 'az', 'entity' => 'アゼルバイジャン', 'idn' => null, 'dnssec' => false),
				'ba'				=> array('name' => 'ba', 'entity' => 'ボスニア・ヘルツェゴビナ', 'idn' => null, 'dnssec' => false),
				'bb'				=> array('name' => 'bb', 'entity' => 'バルバドス', 'idn' => null, 'dnssec' => false),
				'bd'				=> array('name' => 'bd', 'entity' => 'バングラデシュ', 'idn' => true, 'dnssec' => false),
				'be'				=> array('name' => 'be', 'entity' => 'ベルギー', 'idn' => true, 'dnssec' => true),
				'bf'				=> array('name' => 'bf', 'entity' => 'ブルキナファソ', 'idn' => null, 'dnssec' => false),
				'bg'				=> array('name' => 'bg', 'entity' => 'ブルガリア', 'idn' => true, 'dnssec' => true),
				'bh'				=> array('name' => 'bh', 'entity' => 'バーレーン', 'idn' => null, 'dnssec' => false),
				'bi'				=> array('name' => 'bi', 'entity' => 'ブルンジ', 'idn' => null, 'dnssec' => false),
				'bj'				=> array('name' => 'bj', 'entity' => 'ベナン', 'idn' => null, 'dnssec' => false),
				'bm'				=> array('name' => 'bm', 'entity' => 'バミューダ諸島', 'idn' => null, 'dnssec' => false),
				'bn'				=> array('name' => 'bn', 'entity' => 'ブルネイ', 'idn' => null, 'dnssec' => false),
				'bo'				=> array('name' => 'bo', 'entity' => 'ボリビア', 'idn' => null, 'dnssec' => false),
				'bq'				=> array('name' => 'bq', 'entity' => 'ボネール島', 'idn' => null, 'dnssec' => null),
				'br'				=> array('name' => 'br', 'entity' => 'ブラジル', 'idn' => true, 'dnssec' => true),
				'bs'				=> array('name' => 'bs', 'entity' => 'バハマ', 'idn' => null, 'dnssec' => false),
				'bt'				=> array('name' => 'bt', 'entity' => 'ブータン', 'idn' => null, 'dnssec' => false),
				'bv'				=> array('name' => 'bv', 'entity' => 'ブーベ島', 'idn' => false, 'dnssec' => false),
				'bw'				=> array('name' => 'bw', 'entity' => 'ボツワナ', 'idn' => null, 'dnssec' => false),
				'by'				=> array('name' => 'by', 'entity' => 'ベラルーシ', 'idn' => null, 'dnssec' => true),
				'bz'				=> array('name' => 'bz', 'entity' => 'ベリーズ', 'idn' => null, 'dnssec' => true),
				'ca'				=> array('name' => 'ca', 'entity' => 'カナダ', 'idn' => true, 'dnssec' => true),
				'cc'				=> array('name' => 'cc', 'entity' => 'ココス諸島', 'idn' => null, 'dnssec' => true),
				'cd'				=> array('name' => 'cd', 'entity' => 'コンゴ民主共和国', 'idn' => null, 'dnssec' => false),
				'cf'				=> array('name' => 'cf', 'entity' => '中央アフリカ共和国', 'idn' => null, 'dnssec' => false),
				'cg'				=> array('name' => 'cg', 'entity' => 'コンゴ共和国', 'idn' => null, 'dnssec' => false),
				'ch'				=> array('name' => 'ch', 'entity' => 'スイス', 'idn' => true, 'dnssec' => true),
				'ci'				=> array('name' => 'ci', 'entity' => 'コートジボワール', 'idn' => null, 'dnssec' => false),
				'ck'				=> array('name' => 'ck', 'entity' => 'クック諸島', 'idn' => null, 'dnssec' => false),
				'cl'				=> array('name' => 'cl', 'entity' => 'チリ', 'idn' => true, 'dnssec' => true),
				'cm'				=> array('name' => 'cm', 'entity' => 'カメルーン', 'idn' => null, 'dnssec' => false),
				'cn'				=> array('name' => 'cn', 'entity' => '中国', 'idn' => null, 'dnssec' => true),
				'co'				=> array('name' => 'co', 'entity' => 'コロンビア', 'idn' => null, 'dnssec' => true),
				'cr'				=> array('name' => 'cr', 'entity' => 'コスタリカ', 'idn' => null, 'dnssec' => true),
				'cu'				=> array('name' => 'cu', 'entity' => 'キューバ', 'idn' => null, 'dnssec' => false),
				'cv'				=> array('name' => 'cv', 'entity' => 'カーボベルデ', 'idn' => null, 'dnssec' => false),
				'cw'				=> array('name' => 'cw', 'entity' => 'キュラソー島', 'idn' => null, 'dnssec' => false),
				'cx'				=> array('name' => 'cx', 'entity' => 'クリスマス島', 'idn' => null, 'dnssec' => true),
				'cy'				=> array('name' => 'cy', 'entity' => 'キプロス', 'idn' => null, 'dnssec' => false),
				'cz'				=> array('name' => 'cz', 'entity' => 'チェコ', 'idn' => false, 'dnssec' => true),
				'de'				=> array('name' => 'de', 'entity' => 'ドイツ', 'idn' => true, 'dnssec' => true),
				'dj'				=> array('name' => 'dj', 'entity' => 'ジブチ', 'idn' => null, 'dnssec' => false),
				'dk'				=> array('name' => 'dk', 'entity' => 'デンマーク', 'idn' => true, 'dnssec' => true),
				'dm'				=> array('name' => 'dm', 'entity' => 'ドミニカ国', 'idn' => null, 'dnssec' => false),
				'do'				=> array('name' => 'do', 'entity' => 'ドミニカ共和国', 'idn' => null, 'dnssec' => false),
				'dz'				=> array('name' => 'dz', 'entity' => 'アルジェリア', 'idn' => null, 'dnssec' => false),
				'ec'				=> array('name' => 'ec', 'entity' => 'エクアドル', 'idn' => null, 'dnssec' => false),
				'ee'				=> array('name' => 'ee', 'entity' => 'エストニア', 'idn' => true, 'dnssec' => true),
				'eg'				=> array('name' => 'eg', 'entity' => 'エジプト', 'idn' => null, 'dnssec' => false),
				'eh'				=> array('name' => 'eh', 'entity' => '西サハラ', 'idn' => null, 'dnssec' => null),
				'er'				=> array('name' => 'er', 'entity' => 'エリトリア', 'idn' => null, 'dnssec' => false),
				'es'				=> array('name' => 'es', 'entity' => 'スペイン', 'idn' => null, 'dnssec' => true),
				'et'				=> array('name' => 'et', 'entity' => 'エチオピア', 'idn' => null, 'dnssec' => false),
				'eu'				=> array('name' => 'eu', 'entity' => '欧州連合', 'idn' => true, 'dnssec' => true),
				'fi'				=> array('name' => 'fi', 'entity' => 'フィンランド', 'idn' => true, 'dnssec' => true),
				'fj'				=> array('name' => 'fj', 'entity' => 'フィジー', 'idn' => null, 'dnssec' => false),
				'fk'				=> array('name' => 'fk', 'entity' => 'フォークランド諸島', 'idn' => null, 'dnssec' => false),
				'fm'				=> array('name' => 'fm', 'entity' => 'ミクロネシア連邦', 'idn' => null, 'dnssec' => false),
				'fo'				=> array('name' => 'fo', 'entity' => 'フェロー諸島', 'idn' => null, 'dnssec' => true),
				'fr'				=> array('name' => 'fr', 'entity' => 'フランス', 'idn' => true, 'dnssec' => true),
				'ga'				=> array('name' => 'ga', 'entity' => 'ガボン', 'idn' => null, 'dnssec' => false),
				'gb'				=> array('name' => 'gb', 'entity' => 'イギリス', 'idn' => null, 'dnssec' => false),
				'gd'				=> array('name' => 'gd', 'entity' => 'グレナダ', 'idn' => null, 'dnssec' => true),
				'ge'				=> array('name' => 'ge', 'entity' => 'ジョージア', 'idn' => false, 'dnssec' => false),
				'gf'				=> array('name' => 'gf', 'entity' => 'フランス領ギアナ', 'idn' => null, 'dnssec' => false),
				'gg'				=> array('name' => 'gg', 'entity' => 'ガーンジー島', 'idn' => null, 'dnssec' => false),
				'gh'				=> array('name' => 'gh', 'entity' => 'ガーナ', 'idn' => null, 'dnssec' => false),
				'gi'				=> array('name' => 'gi', 'entity' => 'ジブラルタル', 'idn' => null, 'dnssec' => true),
				'gl'				=> array('name' => 'gl', 'entity' => 'グリーンランド', 'idn' => null, 'dnssec' => true),
				'gm'				=> array('name' => 'gm', 'entity' => 'ガンビア', 'idn' => null, 'dnssec' => false),
				'gn'				=> array('name' => 'gn', 'entity' => 'ギニア', 'idn' => null, 'dnssec' => true),
				'gp'				=> array('name' => 'gp', 'entity' => 'グアドループ', 'idn' => null, 'dnssec' => false),
				'gq'				=> array('name' => 'gq', 'entity' => '赤道ギニア', 'idn' => null, 'dnssec' => false),
				'gr'				=> array('name' => 'gr', 'entity' => 'ギリシャ', 'idn' => true, 'dnssec' => true),
				'gs'				=> array('name' => 'gs', 'entity' => 'サウスジョージア・サウスサンドウィッチ諸島', 'idn' => null, 'dnssec' => true),
				'gt'				=> array('name' => 'gt', 'entity' => 'グアテマラ', 'idn' => true, 'dnssec' => false),
				'gu'				=> array('name' => 'gu', 'entity' => 'グアム', 'idn' => null, 'dnssec' => false),
				'gw'				=> array('name' => 'gw', 'entity' => 'ギニアビサウ', 'idn' => null, 'dnssec' => false),
				'gy'				=> array('name' => 'gy', 'entity' => 'ガイアナ', 'idn' => null, 'dnssec' => false),
				'hk'				=> array('name' => 'hk', 'entity' => '香港', 'idn' => true, 'dnssec' => false),
				'hm'				=> array('name' => 'hm', 'entity' => 'ハード島とマクドナルド諸島', 'idn' => null, 'dnssec' => false),
				'hn'				=> array('name' => 'hn', 'entity' => 'ホンジュラス', 'idn' => null, 'dnssec' => true),
				'hr'				=> array('name' => 'hr', 'entity' => 'クロアチア', 'idn' => null, 'dnssec' => true),
				'ht'				=> array('name' => 'ht', 'entity' => 'ハイチ', 'idn' => true, 'dnssec' => false),
				'hu'				=> array('name' => 'hu', 'entity' => 'ハンガリー', 'idn' => null, 'dnssec' => true),
				'id'				=> array('name' => 'id', 'entity' => 'インドネシア', 'idn' => true, 'dnssec' => true),
				'ie'				=> array('name' => 'ie', 'entity' => 'アイルランド', 'idn' => false, 'dnssec' => true),
				'il'				=> array('name' => 'il', 'entity' => 'イスラエル', 'idn' => true, 'dnssec' => false),
				'im'				=> array('name' => 'im', 'entity' => 'マン島', 'idn' => null, 'dnssec' => false),
				'in'				=> array('name' => 'in', 'entity' => 'インド', 'idn' => null, 'dnssec' => true),
				'io'				=> array('name' => 'io', 'entity' => 'イギリス領インド洋地域', 'idn' => null, 'dnssec' => true),
				'iq'				=> array('name' => 'iq', 'entity' => 'イラク', 'idn' => null, 'dnssec' => true),
				'ir'				=> array('name' => 'ir', 'entity' => 'イラン', 'idn' => true, 'dnssec' => false),
				'is'				=> array('name' => 'is', 'entity' => 'アイスランド', 'idn' => true, 'dnssec' => true),
				'it'				=> array('name' => 'it', 'entity' => 'イタリア', 'idn' => true, 'dnssec' => false),
				'je'				=> array('name' => 'je', 'entity' => 'ジャージー島', 'idn' => null, 'dnssec' => false),
				'jm'				=> array('name' => 'jm', 'entity' => 'ジャマイカ', 'idn' => null, 'dnssec' => false),
				'jo'				=> array('name' => 'jo', 'entity' => 'ヨルダン', 'idn' => null, 'dnssec' => false),
				'jp'				=> array('name' => 'jp', 'entity' => '日本', 'idn' => null, 'dnssec' => true),
				'ke'				=> array('name' => 'ke', 'entity' => 'ケニア', 'idn' => null, 'dnssec' => true),
				'kg'				=> array('name' => 'kg', 'entity' => 'キルギス', 'idn' => null, 'dnssec' => true),
				'kh'				=> array('name' => 'kh', 'entity' => 'カンボジア', 'idn' => null, 'dnssec' => false),
				'ki'				=> array('name' => 'ki', 'entity' => 'キリバス', 'idn' => null, 'dnssec' => true),
				'km'				=> array('name' => 'km', 'entity' => 'コモロ', 'idn' => null, 'dnssec' => false),
				'kn'				=> array('name' => 'kn', 'entity' => 'セントクリストファー・ネイビス', 'idn' => null, 'dnssec' => false),
				'kp'				=> array('name' => 'kp', 'entity' => '朝鮮民主主義人民共和国', 'idn' => null, 'dnssec' => false),
				'kr'				=> array('name' => 'kr', 'entity' => '韓国', 'idn' => true, 'dnssec' => true),
				'krd'				=> array('name' => 'krd', 'entity' => 'クルディスタン地域', 'idn' => null, 'dnssec' => true),
				'kw'				=> array('name' => 'kw', 'entity' => 'クウェート', 'idn' => null, 'dnssec' => false),
				'ky'				=> array('name' => 'ky', 'entity' => 'ケイマン諸島', 'idn' => null, 'dnssec' => true),
				'kz'				=> array('name' => 'kz', 'entity' => 'カザフスタン', 'idn' => null, 'dnssec' => false),
				'la'				=> array('name' => 'la', 'entity' => 'ラオス', 'idn' => null, 'dnssec' => true),
				'lb'				=> array('name' => 'lb', 'entity' => 'レバノン', 'idn' => null, 'dnssec' => true),
				'lc'				=> array('name' => 'lc', 'entity' => 'セントルシア', 'idn' => null, 'dnssec' => true),
				'li'				=> array('name' => 'li', 'entity' => 'リヒテンシュタイン', 'idn' => true, 'dnssec' => true),
				'lk'				=> array('name' => 'lk', 'entity' => 'スリランカ', 'idn' => null, 'dnssec' => true),
				'lr'				=> array('name' => 'lr', 'entity' => 'リベリア', 'idn' => null, 'dnssec' => true),
				'ls'				=> array('name' => 'ls', 'entity' => 'レソト', 'idn' => null, 'dnssec' => false),
				'lt'				=> array('name' => 'lt', 'entity' => 'リトアニア', 'idn' => true, 'dnssec' => true),
				'lu'				=> array('name' => 'lu', 'entity' => 'ルクセンブルク', 'idn' => true, 'dnssec' => true),
				'lv'				=> array('name' => 'lv', 'entity' => 'ラトビア', 'idn' => true, 'dnssec' => true),
				'ly'				=> array('name' => 'ly', 'entity' => 'リビア', 'idn' => null, 'dnssec' => false),
				'ma'				=> array('name' => 'ma', 'entity' => 'モロッコ', 'idn' => null, 'dnssec' => true),
				'mc'				=> array('name' => 'mc', 'entity' => 'モナコ', 'idn' => null, 'dnssec' => false),
				'md'				=> array('name' => 'md', 'entity' => 'モルドバ', 'idn' => null, 'dnssec' => false),
				'me'				=> array('name' => 'me', 'entity' => 'モンテネグロ', 'idn' => null, 'dnssec' => true),
				'mg'				=> array('name' => 'mg', 'entity' => 'マダガスカル', 'idn' => null, 'dnssec' => false),
				'mh'				=> array('name' => 'mh', 'entity' => 'マーシャル諸島', 'idn' => null, 'dnssec' => false),
				'mk'				=> array('name' => 'mk', 'entity' => 'マケドニア共和国', 'idn' => null, 'dnssec' => false),
				'ml'				=> array('name' => 'ml', 'entity' => 'マリ', 'idn' => null, 'dnssec' => false),
				'mm'				=> array('name' => 'mm', 'entity' => 'ミャンマー', 'idn' => null, 'dnssec' => true),
				'mn'				=> array('name' => 'mn', 'entity' => 'モンゴル', 'idn' => null, 'dnssec' => true),
				'mo'				=> array('name' => 'mo', 'entity' => 'マカオ', 'idn' => null, 'dnssec' => false),
				'mp'				=> array('name' => 'mp', 'entity' => '北マリアナ諸島', 'idn' => null, 'dnssec' => false),
				'mq'				=> array('name' => 'mq', 'entity' => 'マルティニーク', 'idn' => null, 'dnssec' => false),
				'mr'				=> array('name' => 'mr', 'entity' => 'モーリタニア', 'idn' => null, 'dnssec' => false),
				'ms'				=> array('name' => 'ms', 'entity' => 'モントセラト', 'idn' => null, 'dnssec' => false),
				'mt'				=> array('name' => 'mt', 'entity' => 'マルタ', 'idn' => null, 'dnssec' => false),
				'mu'				=> array('name' => 'mu', 'entity' => 'モーリシャス', 'idn' => null, 'dnssec' => false),
				'mv'				=> array('name' => 'mv', 'entity' => 'モルディブ', 'idn' => null, 'dnssec' => false),
				'mw'				=> array('name' => 'mw', 'entity' => 'マラウイ', 'idn' => null, 'dnssec' => false),
				'mx'				=> array('name' => 'mx', 'entity' => 'メキシコ', 'idn' => null, 'dnssec' => true),
				'my'				=> array('name' => 'my', 'entity' => 'マレーシア', 'idn' => true, 'dnssec' => true),
				'mz'				=> array('name' => 'mz', 'entity' => 'モザンビーク', 'idn' => null, 'dnssec' => false),
				'na'				=> array('name' => 'na', 'entity' => 'ナミビア', 'idn' => null, 'dnssec' => true),
				'nc'				=> array('name' => 'nc', 'entity' => 'ニューカレドニア', 'idn' => null, 'dnssec' => true),
				'ne'				=> array('name' => 'ne', 'entity' => 'ニジェール', 'idn' => null, 'dnssec' => false),
				'nf'				=> array('name' => 'nf', 'entity' => 'ノーフォーク島', 'idn' => null, 'dnssec' => true),
				'ng'				=> array('name' => 'ng', 'entity' => 'ナイジェリア', 'idn' => null, 'dnssec' => false),
				'ni'				=> array('name' => 'ni', 'entity' => 'ニカラグア', 'idn' => null, 'dnssec' => false),
				'nl'				=> array('name' => 'nl', 'entity' => 'オランダ', 'idn' => false, 'dnssec' => true),
				'no'				=> array('name' => 'no', 'entity' => 'ノルウェー', 'idn' => true, 'dnssec' => true),
				'np'				=> array('name' => 'np', 'entity' => 'ネパール', 'idn' => null, 'dnssec' => false),
				'nr'				=> array('name' => 'nr', 'entity' => 'ナウル', 'idn' => null, 'dnssec' => false),
				'nu'				=> array('name' => 'nu', 'entity' => 'ニウエ', 'idn' => true, 'dnssec' => true),
				'nz'				=> array('name' => 'nz', 'entity' => 'ニュージーランド', 'idn' => true, 'dnssec' => true),
				'om'				=> array('name' => 'om', 'entity' => 'オマーン', 'idn' => null, 'dnssec' => false),
				'pa'				=> array('name' => 'pa', 'entity' => 'パナマ', 'idn' => null, 'dnssec' => false),
				'pe'				=> array('name' => 'pe', 'entity' => 'ペルー', 'idn' => true, 'dnssec' => true),
				'pf'				=> array('name' => 'pf', 'entity' => 'フランス領ポリネシア', 'idn' => null, 'dnssec' => false),
				'pg'				=> array('name' => 'pg', 'entity' => 'パプアニューギニア', 'idn' => null, 'dnssec' => false),
				'ph'				=> array('name' => 'ph', 'entity' => 'フィリピン', 'idn' => null, 'dnssec' => false),
				'pk'				=> array('name' => 'pk', 'entity' => 'パキスタン', 'idn' => null, 'dnssec' => false),
				'pl'				=> array('name' => 'pl', 'entity' => 'ポーランド', 'idn' => true, 'dnssec' => true),
				'pm'				=> array('name' => 'pm', 'entity' => 'サンピエール島・ミクロン島', 'idn' => true, 'dnssec' => true),
				'pn'				=> array('name' => 'pn', 'entity' => 'ピトケアン諸島', 'idn' => null, 'dnssec' => false),
				'pr'				=> array('name' => 'pr', 'entity' => 'プエルトリコ', 'idn' => null, 'dnssec' => true),
				'ps'				=> array('name' => 'ps', 'entity' => 'パレスチナ', 'idn' => null, 'dnssec' => false),
				'pt'				=> array('name' => 'pt', 'entity' => 'ポルトガル', 'idn' => true, 'dnssec' => true),
				'pw'				=> array('name' => 'pw', 'entity' => 'パラオ', 'idn' => null, 'dnssec' => true),
				'py'				=> array('name' => 'py', 'entity' => 'パラグアイ', 'idn' => null, 'dnssec' => false),
				'qa'				=> array('name' => 'qa', 'entity' => 'カタール', 'idn' => null, 'dnssec' => false),
				're'				=> array('name' => 're', 'entity' => 'レユニオン', 'idn' => true, 'dnssec' => true),
				'ro'				=> array('name' => 'ro', 'entity' => 'ルーマニア', 'idn' => null, 'dnssec' => false),
				'rs'				=> array('name' => 'rs', 'entity' => 'セルビア', 'idn' => null, 'dnssec' => false),
				'ru'				=> array('name' => 'ru', 'entity' => 'ロシア', 'idn' => false, 'dnssec' => true),
				'rw'				=> array('name' => 'rw', 'entity' => 'ルワンダ', 'idn' => null, 'dnssec' => false),
				'sa'				=> array('name' => 'sa', 'entity' => 'サウジアラビア', 'idn' => true, 'dnssec' => false),
				'sb'				=> array('name' => 'sb', 'entity' => 'ソロモン諸島', 'idn' => null, 'dnssec' => true),
				'sc'				=> array('name' => 'sc', 'entity' => 'セーシェル', 'idn' => null, 'dnssec' => true),
				'sd'				=> array('name' => 'sd', 'entity' => 'スーダン', 'idn' => null, 'dnssec' => false),
				'se'				=> array('name' => 'se', 'entity' => 'スウェーデン', 'idn' => true, 'dnssec' => true),
				'sg'				=> array('name' => 'sg', 'entity' => 'シンガポール', 'idn' => null, 'dnssec' => false),
				'sh'				=> array('name' => 'sh', 'entity' => 'セントヘレナ', 'idn' => true, 'dnssec' => true),
				'si'				=> array('name' => 'si', 'entity' => 'スロベニア', 'idn' => true, 'dnssec' => true),
				'sj'				=> array('name' => 'sj', 'entity' => 'スヴァールバル諸島・', 'idn' => false, 'dnssec' => true),
				'sk'				=> array('name' => 'sk', 'entity' => 'ヤンマイエン島', 'idn' => null, 'dnssec' => false),
				'sl'				=> array('name' => 'sl', 'entity' => 'スロバキア', 'idn' => null, 'dnssec' => false),
				'sm'				=> array('name' => 'sm', 'entity' => 'シエラレオネ', 'idn' => null, 'dnssec' => false),
				'sn'				=> array('name' => 'sn', 'entity' => 'サンマリノ', 'idn' => null, 'dnssec' => false),
				'so'				=> array('name' => 'so', 'entity' => 'セネガル', 'idn' => false, 'dnssec' => false),
				'sr'				=> array('name' => 'sr', 'entity' => 'ソマリア', 'idn' => null, 'dnssec' => false),
				'ss'				=> array('name' => 'ss', 'entity' => 'スリナム', 'idn' => null, 'dnssec' => null),
				'st'				=> array('name' => 'st', 'entity' => '南スーダン', 'idn' => null, 'dnssec' => false),
				'su'				=> array('name' => 'su', 'entity' => 'サントメ・プリンシペ', 'idn' => true, 'dnssec' => true),
				'sv'				=> array('name' => 'sv', 'entity' => 'ソビエト連邦', 'idn' => null, 'dnssec' => false),
				'sx'				=> array('name' => 'sx', 'entity' => 'エルサルバドル', 'idn' => null, 'dnssec' => true),
				'sy'				=> array('name' => 'sy', 'entity' => 'シント・マールテン', 'idn' => null, 'dnssec' => false),
				'sz'				=> array('name' => 'sz', 'entity' => 'シリア', 'idn' => null, 'dnssec' => false),
				'tc'				=> array('name' => 'tc', 'entity' => 'スワジランド', 'idn' => null, 'dnssec' => false),
				'td'				=> array('name' => 'td', 'entity' => 'タークス・カイコス諸島', 'idn' => null, 'dnssec' => false),
				'tf'				=> array('name' => 'tf', 'entity' => 'チャド', 'idn' => true, 'dnssec' => true),
				'tg'				=> array('name' => 'tg', 'entity' => 'フランス領南方・南極地域', 'idn' => null, 'dnssec' => false),
				'th'				=> array('name' => 'th', 'entity' => 'トーゴ', 'idn' => true, 'dnssec' => true),
				'tj'				=> array('name' => 'tj', 'entity' => 'タイ', 'idn' => null, 'dnssec' => false),
				'tk'				=> array('name' => 'tk', 'entity' => 'タジキスタン', 'idn' => null, 'dnssec' => false),
				'tl'				=> array('name' => 'tl', 'entity' => 'トケラウ', 'idn' => null, 'dnssec' => false),
				'tm'				=> array('name' => 'tm', 'entity' => '東ティモール', 'idn' => true, 'dnssec' => true),
				'tn'				=> array('name' => 'tn', 'entity' => 'トルクメニスタン', 'idn' => null, 'dnssec' => true),
				'to'				=> array('name' => 'to', 'entity' => 'チュニジア', 'idn' => true, 'dnssec' => false),
				'tp'				=> array('name' => 'tp', 'entity' => 'トンガ', 'idn' => null, 'dnssec' => false),
				'tr'				=> array('name' => 'tr', 'entity' => '東ティモール', 'idn' => true, 'dnssec' => false),
				'tt'				=> array('name' => 'tt', 'entity' => 'トルコ', 'idn' => null, 'dnssec' => true),
				'tv'				=> array('name' => 'tv', 'entity' => 'トリニダード・トバゴ', 'idn' => null, 'dnssec' => true),
				'tw'				=> array('name' => 'tw', 'entity' => 'ツバル', 'idn' => true, 'dnssec' => true),
				'tz'				=> array('name' => 'tz', 'entity' => '台湾', 'idn' => null, 'dnssec' => true),
				'ua'				=> array('name' => 'ua', 'entity' => 'タンザニア', 'idn' => null, 'dnssec' => true),
				'ug'				=> array('name' => 'ug', 'entity' => 'ウクライナ', 'idn' => null, 'dnssec' => true),
				'uk'				=> array('name' => 'uk', 'entity' => 'ウガンダ', 'idn' => null, 'dnssec' => true),
				'us'				=> array('name' => 'us', 'entity' => 'イギリス', 'idn' => null, 'dnssec' => true),
				'uy'				=> array('name' => 'uy', 'entity' => 'アメリカ', 'idn' => null, 'dnssec' => true),
				'uz'				=> array('name' => 'uz', 'entity' => 'ウルグアイ', 'idn' => null, 'dnssec' => false),
				'va'				=> array('name' => 'va', 'entity' => 'ウズベキスタン', 'idn' => null, 'dnssec' => false),
				'vc'				=> array('name' => 'vc', 'entity' => 'バチカン市国', 'idn' => null, 'dnssec' => true),
				've'				=> array('name' => 've', 'entity' => 'セントビンセント・グレナディーン', 'idn' => null, 'dnssec' => false),
				'vg'				=> array('name' => 'vg', 'entity' => 'ベネズエラ', 'idn' => null, 'dnssec' => false),
				'vi'				=> array('name' => 'vi', 'entity' => 'イギリス領ヴァージン諸島', 'idn' => null, 'dnssec' => false),
				'vn'				=> array('name' => 'vn', 'entity' => 'アメリカ領ヴァージン諸島', 'idn' => true, 'dnssec' => false),
				'vu'				=> array('name' => 'vu', 'entity' => 'ベトナム', 'idn' => null, 'dnssec' => true),
				'wf'				=> array('name' => 'wf', 'entity' => 'バヌアツ', 'idn' => true, 'dnssec' => true),
				'ws'				=> array('name' => 'ws', 'entity' => 'ウォリス・フツナ', 'idn' => true, 'dnssec' => true),
				'ye'				=> array('name' => 'ye', 'entity' => 'サモア', 'idn' => null, 'dnssec' => false),
				'yt'				=> array('name' => 'yt', 'entity' => 'イエメン', 'idn' => true, 'dnssec' => true),
				'za'				=> array('name' => 'za', 'entity' => 'マヨット島', 'idn' => null, 'dnssec' => false),
				'zm'				=> array('name' => 'zm', 'entity' => '南アフリカ', 'idn' => null, 'dnssec' => true),
				'zw'				=> array('name' => 'zw', 'entity' => 'ザンビア', 'idn' => null, 'dnssec' => false),
				'academy'			=> array('name' => 'academy', 'entity' => 'ジンバブエ', 'idn' => true, 'dnssec' => false),
				'الجزائر'				=> array('name' => 'الجزائر', 'entity' => 'アルジェリア', 'idn' => true, 'dnssec' => false),
				'հայ'				=> array('name' => 'հայ', 'entity' => 'アルメニア', 'idn' => true, 'dnssec' => true),
				'বাংলা'				=> array('name' => 'বাংলা', 'entity' => 'バングラデシュ', 'idn' => true, 'dnssec' => false),
				'бел'				=> array('name' => 'бел', 'entity' => 'ベラルーシ', 'idn' => true, 'dnssec' => false),
				'бг'				=> array('name' => 'бг', 'entity' => 'ブルガリア', 'idn' => true, 'dnssec' => false),
				'中国'				=> array('name' => '中国', 'entity' => '中国', 'idn' => true, 'dnssec' => true),
				'中國'				=> array('name' => '中國', 'entity' => '中国', 'idn' => true, 'dnssec' => true),
				'مصر'				=> array('name' => 'مصر', 'entity' => 'エジプト', 'idn' => true, 'dnssec' => true),
				'ею'				=> array('name' => 'ею', 'entity' => '欧州連合', 'idn' => true, 'dnssec' => false),
				'გე'					=> array('name' => 'გე', 'entity' => 'ジョージア', 'idn' => true, 'dnssec' => false),
				'ελ'				=> array('name' => 'ελ', 'entity' => 'ギリシャ', 'idn' => true, 'dnssec' => false),
				'香港'				=> array('name' => '香港', 'entity' => '香港', 'idn' => true, 'dnssec' => false),
				'भारत'				=> array('name' => 'भारत', 'entity' => 'インド', 'idn' => true, 'dnssec' => true),
				'بھارت'				=> array('name' => 'بھارت', 'entity' => 'インド', 'idn' => true, 'dnssec' => true),
				'భారత్'				=> array('name' => 'భారత్', 'entity' => 'インド', 'idn' => true, 'dnssec' => true),
				'ભારત'				=> array('name' => 'ભારત', 'entity' => 'インド', 'idn' => true, 'dnssec' => true),
				'ਭਾਰਤ'				=> array('name' => 'ਭਾਰਤ', 'entity' => 'インド', 'idn' => true, 'dnssec' => true),
				'இந்தியா'			=> array('name' => 'இந்தியா', 'entity' => 'インド', 'idn' => true, 'dnssec' => true),
				'ভারত'				=> array('name' => 'ভারত', 'entity' => 'インド', 'idn' => true, 'dnssec' => true),
				'ایران'				=> array('name' => 'ایران', 'entity' => 'イラン', 'idn' => true, 'dnssec' => false),
				'عراق'				=> array('name' => 'عراق', 'entity' => 'イラク', 'idn' => true, 'dnssec' => false),
				'الاردن'				=> array('name' => 'الاردن', 'entity' => 'ヨルダン', 'idn' => true, 'dnssec' => false),
				'қаз'				=> array('name' => 'қаз', 'entity' => 'カザフスタン', 'idn' => true, 'dnssec' => false),
				'澳门'				=> array('name' => '澳门', 'entity' => 'マカオ', 'idn' => true, 'dnssec' => false),
				'澳門'				=> array('name' => '澳門', 'entity' => 'マカオ', 'idn' => true, 'dnssec' => false),
				'мкд'				=> array('name' => 'мкд', 'entity' => 'マケドニア共和国', 'idn' => true, 'dnssec' => false),
				'مليسيا'				=> array('name' => 'مليسيا', 'entity' => 'マレーシア', 'idn' => true, 'dnssec' => true),
				'мон'				=> array('name' => 'мон', 'entity' => 'モンゴル', 'idn' => true, 'dnssec' => true),
				'المغرب'				=> array('name' => 'المغرب', 'entity' => 'モロッコ', 'idn' => true, 'dnssec' => false),
				'عمان'				=> array('name' => 'عمان', 'entity' => 'オマーン', 'idn' => true, 'dnssec' => false),
				'پاکستان'				=> array('name' => 'پاکستان', 'entity' => 'パキスタン', 'idn' => true, 'dnssec' => false),
				'فلسطين'				=> array('name' => 'فلسطين', 'entity' => 'パレスチナ', 'idn' => true, 'dnssec' => false),
				'قطر'					=> array('name' => 'قطر', 'entity' => 'カタール', 'idn' => true, 'dnssec' => false),
				'рф'				=> array('name' => 'рф', 'entity' => 'ロシア', 'idn' => true, 'dnssec' => true),
				'السعودية'				=> array('name' => 'السعودية', 'entity' => 'サウジアラビア', 'idn' => true, 'dnssec' => false),
				'срб'				=> array('name' => 'срб', 'entity' => 'セルビア', 'idn' => true, 'dnssec' => false),
				'新加坡'				=> array('name' => '新加坡', 'entity' => 'シンガポール', 'idn' => true, 'dnssec' => false),
				'சிங்கப்ப ூர்'			=> array('name' => 'சிங்கப்பூர்', 'entity' => 'シンガポール', 'idn' => true, 'dnssec' => false),
				'한국'				=> array('name' => '한국', 'entity' => '韓国', 'idn' => true, 'dnssec' => true),
				'ලංකා'				=> array('name' => 'ලංකා', 'entity' => 'スリランカ', 'idn' => true, 'dnssec' => true),
				'இலங்கை'			=> array('name' => 'இலங்கை', 'entity' => 'スリランカ', 'idn' => true, 'dnssec' => true),
				'سودان'				=> array('name' => 'سودان', 'entity' => 'スーダン', 'idn' => true, 'dnssec' => false),
				'سورية'				=> array('name' => 'سورية', 'entity' => 'シリア', 'idn' => true, 'dnssec' => false),
				'台湾'				=> array('name' => '台湾', 'entity' => '台湾', 'idn' => true, 'dnssec' => true),
				'台灣'				=> array('name' => '台灣', 'entity' => '台湾', 'idn' => true, 'dnssec' => true),
				'ไทย'				=> array('name' => 'ไทย', 'entity' => 'タイ', 'idn' => true, 'dnssec' => true),
				'تونس'				=> array('name' => 'تونس', 'entity' => 'チュニジア', 'idn' => true, 'dnssec' => true),
				'укр'				=> array('name' => 'укр', 'entity' => 'ウクライナ', 'idn' => true, 'dnssec' => false),
				'امارات'				=> array('name' => 'امارات', 'entity' => 'アラブ首長国連邦', 'idn' => true, 'dnssec' => false),
				'اليمن'				=> array('name' => 'اليمن', 'entity' => 'イエメン', 'idn' => true, 'dnssec' => false),
				'academy'			=> array('name' => 'academy', 'entity' => 'academic institutes', 'idn' => true, 'dnssec' => true),
				'accountant'		=> array('name' => 'accountant', 'entity' => 'accountants and accounting firms', 'idn' => null, 'dnssec' => true),
				'accountants'		=> array('name' => 'accountants', 'entity' => 'accountants and accounting firms', 'idn' => true, 'dnssec' => true),
				'active'			=> array('name' => 'active', 'entity' => 'general', 'idn' => null, 'dnssec' => true),
				'actor'				=> array('name' => 'actor', 'entity' => 'actors', 'idn' => true, 'dnssec' => true),
				'adult'				=> array('name' => 'adult', 'entity' => 'adult entertainment (pornography)', 'idn' => true, 'dnssec' => true),
				'aero'				=> array('name' => 'aero', 'entity' => '航空業界', 'idn' => false, 'dnssec' => false),
				'agency'			=> array('name' => 'agency', 'entity' => 'business associations', 'idn' => true, 'dnssec' => true),
				'airforce'			=> array('name' => 'airforce', 'entity' => 'defense contractors', 'idn' => null, 'dnssec' => true),
				'apartments'		=> array('name' => 'apartments', 'entity' => 'apartments', 'idn' => true, 'dnssec' => true),
				'app'				=> array('name' => 'app', 'entity' => 'Phone apps', 'idn' => null, 'dnssec' => true),
				'archi'				=> array('name' => 'archi', 'entity' => 'architects and architect firms', 'idn' => null, 'dnssec' => true),
				'army'				=> array('name' => 'army', 'entity' => 'defense contractors', 'idn' => null, 'dnssec' => true),
				'associates'		=> array('name' => 'associates', 'entity' => 'business associations', 'idn' => true, 'dnssec' => true),
				'attorney'			=> array('name' => 'attorney', 'entity' => 'attorneys and legal organizations', 'idn' => null, 'dnssec' => true),
				'auction'			=> array('name' => 'auction', 'entity' => 'auction', 'idn' => null, 'dnssec' => true),
				'audio'				=> array('name' => 'audio', 'entity' => 'stereo/sound systems, music', 'idn' => true, 'dnssec' => true),
				'autos'				=> array('name' => 'autos', 'entity' => 'autos', 'idn' => null, 'dnssec' => true),
				'band'				=> array('name' => 'band', 'entity' => 'band', 'idn' => null, 'dnssec' => true),
				'bar'				=> array('name' => 'bar', 'entity' => 'Bars and related industry', 'idn' => true, 'dnssec' => true),
				'bargains'			=> array('name' => 'bargains', 'entity' => 'coupons and online sellers', 'idn' => true, 'dnssec' => true),
				'beer'				=> array('name' => 'beer', 'entity' => 'breweries and beer aficionados', 'idn' => null, 'dnssec' => true),
				'best'				=> array('name' => 'best', 'entity' => 'best', 'idn' => null, 'dnssec' => true),
				'bid'				=> array('name' => 'bid', 'entity' => 'auctions', 'idn' => true, 'dnssec' => true),
				'bike'				=> array('name' => 'bike', 'entity' => 'bicycles', 'idn' => true, 'dnssec' => true),
				'bingo'				=> array('name' => 'bingo', 'entity' => 'ビンゴ', 'idn' => true, 'dnssec' => true),
				'bio'				=> array('name' => 'bio', 'entity' => 'biodiversity, biographies', 'idn' => null, 'dnssec' => true),
				'biz'				=> array('name' => 'biz', 'entity' => 'ビジネス', 'idn' => true, 'dnssec' => true),
				'black'				=> array('name' => 'black', 'entity' => 'those who like the color black', 'idn' => true, 'dnssec' => true),
				'blackfriday'		=> array('name' => 'blackfriday', 'entity' => 'ブラックフライデー', 'idn' => true, 'dnssec' => true),
				'blog'				=> array('name' => 'blog', 'entity' => 'Blogs', 'idn' => null, 'dnssec' => true),
				'blue'				=> array('name' => 'blue', 'entity' => 'those who like the color blue', 'idn' => true, 'dnssec' => true),
				'boo'				=> array('name' => 'boo', 'entity' => 'ghosts and spooky business', 'idn' => null, 'dnssec' => true),
				'boutique'			=> array('name' => 'boutique', 'entity' => 'specialized businesses', 'idn' => true, 'dnssec' => true),
				'build'				=> array('name' => 'build', 'entity' => 'construction industry', 'idn' => true, 'dnssec' => true),
				'builders'			=> array('name' => 'builders', 'entity' => 'construction workers', 'idn' => true, 'dnssec' => true),
				'business'			=> array('name' => 'business', 'entity' => 'businesses', 'idn' => true, 'dnssec' => true),
				'buzz'				=> array('name' => 'buzz', 'entity' => 'marketing and social networking', 'idn' => true, 'dnssec' => true),
				'cab'				=> array('name' => 'cab', 'entity' => 'cabs and taxi companies', 'idn' => true, 'dnssec' => true),
				'camera'			=> array('name' => 'camera', 'entity' => 'camera-related businesses', 'idn' => true, 'dnssec' => true),
				'camp'				=> array('name' => 'camp', 'entity' => 'camps and camping', 'idn' => true, 'dnssec' => true),
				'cancerresearch'	=> array('name' => 'cancerresearch', 'entity' => 'Organizations, research institutes and individuals interested in ending cancer through research ', 'idn' => null, 'dnssec' => TRUE),
				'capital'			=> array('name' => 'capital', 'entity' => 'financial firms', 'idn' => true, 'dnssec' => true),
				'cards'				=> array('name' => 'cards', 'entity' => 'general', 'idn' => true, 'dnssec' => true),
				'care'				=> array('name' => 'care', 'entity' => 'healthcare industry', 'idn' => true, 'dnssec' => true),
				'career'			=> array('name' => 'career', 'entity' => 'career', 'idn' => true, 'dnssec' => true),
				'careers'			=> array('name' => 'careers', 'entity' => 'Employment', 'idn' => true, 'dnssec' => true),
				'cash'				=> array('name' => 'cash', 'entity' => 'financial', 'idn' => true, 'dnssec' => true),
				'casino'			=> array('name' => 'casino', 'entity' => 'カジノ', 'idn' => true, 'dnssec' => true),
				'catering'			=> array('name' => 'catering', 'entity' => 'Food service', 'idn' => true, 'dnssec' => true),
				'center'			=> array('name' => 'center', 'entity' => 'general', 'idn' => true, 'dnssec' => true),
				'ceo'				=> array('name' => 'ceo', 'entity' => 'CEOs', 'idn' => null, 'dnssec' => true),
				'channel'			=> array('name' => 'channel', 'entity' => 'channel', 'idn' => null, 'dnssec' => true),
				'chat'				=> array('name' => 'chat', 'entity' => 'online chat', 'idn' => true, 'dnssec' => true),
				'cheap'				=> array('name' => 'cheap', 'entity' => 'Resellers', 'idn' => true, 'dnssec' => true),
				'christmas'			=> array('name' => 'christmas', 'entity' => 'Christmas', 'idn' => true, 'dnssec' => true),
				'church'			=> array('name' => 'church', 'entity' => 'churches', 'idn' => true, 'dnssec' => true),
				'city'				=> array('name' => 'city', 'entity' => 'general', 'idn' => true, 'dnssec' => true),
				'claims'			=> array('name' => 'claims', 'entity' => 'retail, auctions', 'idn' => true, 'dnssec' => true),
				'cleaning'			=> array('name' => 'cleaning', 'entity' => 'Cleaning services', 'idn' => true, 'dnssec' => true),
				'click'				=> array('name' => 'click', 'entity' => 'click', 'idn' => true, 'dnssec' => true),
				'clinic'			=> array('name' => 'clinic', 'entity' => 'healthcare clinics', 'idn' => true, 'dnssec' => true),
				'clothing'			=> array('name' => 'clothing', 'entity' => 'Apparel', 'idn' => true, 'dnssec' => true),
				'club'				=> array('name' => 'club', 'entity' => 'groups, organizations, assemblies, communities, general', 'idn' => true, 'dnssec' => true),
				'coach'				=> array('name' => 'coach', 'entity' => 'travel (flights and motor coaches)', 'idn' => true, 'dnssec' => true),
				'codes'				=> array('name' => 'codes', 'entity' => 'computer and/or encryption code enthusiasts', 'idn' => true, 'dnssec' => true),
				'coffee'			=> array('name' => 'coffee', 'entity' => 'cafés and coffee aficionados', 'idn' => true, 'dnssec' => true),
				'college'			=> array('name' => 'college', 'entity' => 'Educational', 'idn' => true, 'dnssec' => true),
				'community'			=> array('name' => 'community', 'entity' => 'social groups, neighborhoods', 'idn' => true, 'dnssec' => true),
				'company'			=> array('name' => 'company', 'entity' => 'business associations', 'idn' => true, 'dnssec' => true),
				'computer'			=> array('name' => 'computer', 'entity' => 'Technology', 'idn' => true, 'dnssec' => true),
				'condos'			=> array('name' => 'condos', 'entity' => 'Real estate', 'idn' => true, 'dnssec' => true),
				'construction'		=> array('name' => 'construction', 'entity' => 'Construction industry', 'idn' => true, 'dnssec' => true),
				'consulting'		=> array('name' => 'consulting', 'entity' => 'hired advisors', 'idn' => true, 'dnssec' => true),
				'contractors'		=> array('name' => 'contractors', 'entity' => 'Remodeling and independent businesses', 'idn' => true, 'dnssec' => true),
				'cooking'			=> array('name' => 'cooking', 'entity' => 'sharing recipes', 'idn' => true, 'dnssec' => true),
				'cool'				=> array('name' => 'cool', 'entity' => 'General interests', 'idn' => true, 'dnssec' => true),
				'country'			=> array('name' => 'country', 'entity' => 'general', 'idn' => true, 'dnssec' => true),
				'coupons'			=> array('name' => 'coupons', 'entity' => 'coupons', 'idn' => true, 'dnssec' => true),
				'credit'			=> array('name' => 'credit', 'entity' => 'Financial institutions', 'idn' => true, 'dnssec' => true),
				'creditcard'		=> array('name' => 'creditcard', 'entity' => 'Financial institutions', 'idn' => true, 'dnssec' => true),
				'cricket'			=> array('name' => 'cricket', 'entity' => 'クリケット', 'idn' => null, 'dnssec' => true),
				'cruises'			=> array('name' => 'cruises', 'entity' => 'cruise businesses and travel', 'idn' => true, 'dnssec' => true),
				'dad'				=> array('name' => 'dad', 'entity' => 'families', 'idn' => null, 'dnssec' => true),
				'dance'				=> array('name' => 'dance', 'entity' => 'Dance studios and companies', 'idn' => true, 'dnssec' => true),
				'date'				=> array('name' => 'date', 'entity' => 'online dating', 'idn' => null, 'dnssec' => true),
				'dating'			=> array('name' => 'dating', 'entity' => 'online dating', 'idn' => true, 'dnssec' => true),
				'day'				=> array('name' => 'day', 'entity' => 'general', 'idn' => null, 'dnssec' => true),
				'deals'				=> array('name' => 'deals', 'entity' => 'online shopping and couponing', 'idn' => true, 'dnssec' => true),
				'degree'			=> array('name' => 'degree', 'entity' => 'general', 'idn' => null, 'dnssec' => true),
				'delivery'			=> array('name' => 'delivery', 'entity' => 'general', 'idn' => true, 'dnssec' => true),
				'democrat'			=> array('name' => 'democrat', 'entity' => '民主党', 'idn' => true, 'dnssec' => true),
				'dental'			=> array('name' => 'dental', 'entity' => '歯科医', 'idn' => true, 'dnssec' => true),
				'dentist'			=> array('name' => 'dentist', 'entity' => '歯科医', 'idn' => null, 'dnssec' => true),
				'design'			=> array('name' => 'design', 'entity' => 'graphic art and fashion', 'idn' => true, 'dnssec' => true),
				'diamonds'			=> array('name' => 'diamonds', 'entity' => 'diamond and jewelry industry', 'idn' => true, 'dnssec' => true),
				'diet'				=> array('name' => 'diet', 'entity' => 'diet', 'idn' => true, 'dnssec' => true),
				'digital'			=> array('name' => 'digital', 'entity' => 'general', 'idn' => true, 'dnssec' => true),
				'direct'			=> array('name' => 'direct', 'entity' => 'general', 'idn' => null, 'dnssec' => true),
				'directory'			=> array('name' => 'directory', 'entity' => 'general directory', 'idn' => true, 'dnssec' => true),
				'discount'			=> array('name' => 'discount', 'entity' => 'general', 'idn' => true, 'dnssec' => true),
				'dog'				=> array('name' => 'dog', 'entity' => 'dog stores and owners', 'idn' => true, 'dnssec' => true),
				'domains'			=> array('name' => 'domains', 'entity' => 'domain registries', 'idn' => true, 'dnssec' => true),
				'download'			=> array('name' => 'download', 'entity' => 'technology', 'idn' => null, 'dnssec' => true),
				'eat'				=> array('name' => 'eat', 'entity' => 'restaurants and ', 'idn' => null, 'dnssec' => true),
				'education'			=> array('name' => 'education', 'entity' => 'educational institutes', 'idn' => true, 'dnssec' => true),
				'email'				=> array('name' => 'email', 'entity' => 'email', 'idn' => true, 'dnssec' => true),
				'energy'			=> array('name' => 'energy', 'entity' => 'energy industry and marketing', 'idn' => true, 'dnssec' => true),
				'engineer'			=> array('name' => 'engineer', 'entity' => 'engineers and engineering firms', 'idn' => true, 'dnssec' => true),
				'engineering'		=> array('name' => 'engineering', 'entity' => 'engineering firms', 'idn' => true, 'dnssec' => true),
				'equipment'			=> array('name' => 'equipment', 'entity' => 'equipment-related businesses', 'idn' => true, 'dnssec' => true),
				'esq'				=> array('name' => 'esq', 'entity' => 'lawyers, law firms, legal professionals', 'idn' => null, 'dnssec' => true),
				'estate'			=> array('name' => 'estate', 'entity' => 'real estate businesses', 'idn' => true, 'dnssec' => true),
				'events'			=> array('name' => 'events', 'entity' => 'happenings', 'idn' => true, 'dnssec' => true),
				'exchange'			=> array('name' => 'exchange', 'entity' => 'generic trade', 'idn' => true, 'dnssec' => true),
				'expert'			=> array('name' => 'expert', 'entity' => 'generic expertise', 'idn' => true, 'dnssec' => true),
				'exposed'			=> array('name' => 'exposed', 'entity' => 'general interest', 'idn' => true, 'dnssec' => true),
				'express'			=> array('name' => 'express', 'entity' => 'shipping', 'idn' => true, 'dnssec' => true),
				'fail'				=> array('name' => 'fail', 'entity' => 'general', 'idn' => true, 'dnssec' => true),
				'faith'				=> array('name' => 'faith', 'entity' => 'religion and churches', 'idn' => null, 'dnssec' => true),
				'fans'				=> array('name' => 'fans', 'entity' => 'general', 'idn' => null, 'dnssec' => true),
				'farm'				=> array('name' => 'farm', 'entity' => 'farms and agriculture', 'idn' => true, 'dnssec' => true),
				'fashion'			=> array('name' => 'fashion', 'entity' => 'clothing industry', 'idn' => true, 'dnssec' => true),
				'pid'				=> array('name' => 'pid', 'entity' => 'pid', 'idn' => null, 'dnssec' => true),
				'finance'			=> array('name' => 'finance', 'entity' => 'financial', 'idn' => true, 'dnssec' => true),
				'financial'			=> array('name' => 'financial', 'entity' => 'financial', 'idn' => true, 'dnssec' => true),
				'fish'				=> array('name' => 'fish', 'entity' => 'fishing businesses, sports, and interests', 'idn' => true, 'dnssec' => true),
				'fishing'			=> array('name' => 'fishing', 'entity' => 'fishing businesses, sports, and interests', 'idn' => true, 'dnssec' => true),
				'fit'				=> array('name' => 'fit', 'entity' => 'Fitness and exercise', 'idn' => null, 'dnssec' => true),
				'fitness'			=> array('name' => 'fitness', 'entity' => 'Fitness and exercise', 'idn' => true, 'dnssec' => true),
				'flights'			=> array('name' => 'flights', 'entity' => 'airline businesses and travel', 'idn' => true, 'dnssec' => true),
				'florist'			=> array('name' => 'florist', 'entity' => 'florists', 'idn' => true, 'dnssec' => true),
				'flowers'			=> array('name' => 'flowers', 'entity' => 'florists and gardens', 'idn' => true, 'dnssec' => true),
				'fly'				=> array('name' => 'fly', 'entity' => 'travel', 'idn' => null, 'dnssec' => true),
				'foo'				=> array('name' => 'foo', 'entity' => 'web development', 'idn' => null, 'dnssec' => true),
				'football'			=> array('name' => 'football', 'entity' => 'サッカー・アメリカンフットボール', 'idn' => true, 'dnssec' => true),
				'forsale'			=> array('name' => 'forsale', 'entity' => 'online retail', 'idn' => null, 'dnssec' => true),
				'foundation'		=> array('name' => 'foundation', 'entity' => 'charitable organizations', 'idn' => true, 'dnssec' => true),
				'fund'				=> array('name' => 'fund', 'entity' => 'financial', 'idn' => true, 'dnssec' => true),
				'furniture'			=> array('name' => 'furniture', 'entity' => 'furniture businesses', 'idn' => true, 'dnssec' => true),
				'fyi'				=> array('name' => 'fyi', 'entity' => 'for your information', 'idn' => true, 'dnssec' => true),
				'gallery'			=> array('name' => 'gallery', 'entity' => 'photo and art galleries', 'idn' => true, 'dnssec' => true),
				'garden'			=> array('name' => 'garden', 'entity' => 'gardening', 'idn' => true, 'dnssec' => true),
				'gift'				=> array('name' => 'gift', 'entity' => 'gift-giving', 'idn' => true, 'dnssec' => true),
				'gifts'				=> array('name' => 'gifts', 'entity' => 'gift-giving', 'idn' => true, 'dnssec' => true),
				'gives'				=> array('name' => 'gives', 'entity' => 'charities and gift-giving', 'idn' => null, 'dnssec' => true),
				'glass'				=> array('name' => 'glass', 'entity' => 'window sales and repairs', 'idn' => true, 'dnssec' => true),
				'global'			=> array('name' => 'global', 'entity' => 'general', 'idn' => true, 'dnssec' => true),
				'gold'				=> array('name' => 'gold', 'entity' => 'gold and luxury', 'idn' => null, 'dnssec' => true),
				'golf'				=> array('name' => 'golf', 'entity' => 'ゴルフ', 'idn' => true, 'dnssec' => true),
				'gop'				=> array('name' => 'gop', 'entity' => '共和党', 'idn' => true, 'dnssec' => true),
				'graphics'			=> array('name' => 'graphics', 'entity' => 'graphics', 'idn' => true, 'dnssec' => true),
				'green'				=> array('name' => 'green', 'entity' => 'the environmentally-focused', 'idn' => null, 'dnssec' => true),
				'gripe'				=> array('name' => 'gripe', 'entity' => 'opinion sites', 'idn' => true, 'dnssec' => true),
				'guide'				=> array('name' => 'guide', 'entity' => 'help sites', 'idn' => true, 'dnssec' => true),
				'guitars'			=> array('name' => 'guitars', 'entity' => 'Guitars', 'idn' => true, 'dnssec' => true),
				'guru'				=> array('name' => 'guru', 'entity' => 'generic expertise', 'idn' => true, 'dnssec' => true),
				'healthcare'		=> array('name' => 'healthcare', 'entity' => 'healthcare industry', 'idn' => null, 'dnssec' => true),
				'help'				=> array('name' => 'help', 'entity' => 'help sites', 'idn' => true, 'dnssec' => true),
				'here'				=> array('name' => 'here', 'entity' => 'generic geographic', 'idn' => null, 'dnssec' => true),
				'hiphop'			=> array('name' => 'hiphop', 'entity' => 'ヒップホップ文化', 'idn' => true, 'dnssec' => true),
				'hiv'				=> array('name' => 'hiv', 'entity' => 'AIDS・HIV', 'idn' => null, 'dnssec' => true),
				'hockey'			=> array('name' => 'hockey', 'entity' => 'ホッケー', 'idn' => true, 'dnssec' => true),
				'holdings'			=> array('name' => 'holdings', 'entity' => 'real estate or financial business', 'idn' => true, 'dnssec' => true),
				'holiday'			=> array('name' => 'holiday', 'entity' => 'holiday gift industry', 'idn' => true, 'dnssec' => true),
				'homes'				=> array('name' => 'homes', 'entity' => 'individuals interested in real estate and home improvement', 'idn' => null, 'dnssec' => true),
				'horse'				=> array('name' => 'horse', 'entity' => 'horse-related businesses and interest', 'idn' => true, 'dnssec' => true),
				'host'				=> array('name' => 'host', 'entity' => 'network companies', 'idn' => null, 'dnssec' => true),
				'hosting'			=> array('name' => 'hosting', 'entity' => 'hosting', 'idn' => true, 'dnssec' => true),
				'house'				=> array('name' => 'house', 'entity' => 'real estate and construction businesses', 'idn' => true, 'dnssec' => true),
				'how'				=> array('name' => 'how', 'entity' => 'how-to guides', 'idn' => null, 'dnssec' => true),
				'info'				=> array('name' => 'info', 'entity' => '情報', 'idn' => true, 'dnssec' => true),
				'ing'				=> array('name' => 'ing', 'entity' => 'Verbal suffix', 'idn' => null, 'dnssec' => true),
				'ink'				=> array('name' => 'ink', 'entity' => 'creative printing or tattooing', 'idn' => true, 'dnssec' => true),
				'institute'			=> array('name' => 'institute', 'entity' => 'institute', 'idn' => true, 'dnssec' => true),
				'insure'			=> array('name' => 'insure', 'entity' => 'Insurance companies', 'idn' => true, 'dnssec' => true),
				'international'		=> array('name' => 'international', 'entity' => 'international entities', 'idn' => true, 'dnssec' => true),
				'investments'		=> array('name' => 'investments', 'entity' => 'financial', 'idn' => true, 'dnssec' => true),
				'jewelry'			=> array('name' => 'jewelry', 'entity' => 'jewelry stores', 'idn' => true, 'dnssec' => true),
				'jobs'				=> array('name' => 'jobs', 'entity' => '雇用', 'idn' => false, 'dnssec' => true),
				'kim'				=> array('name' => 'kim', 'entity' => 'キム', 'idn' => null, 'dnssec' => true),
				'kitchen'			=> array('name' => 'kitchen', 'entity' => 'food industry and remodeling', 'idn' => true, 'dnssec' => true),
				'land'				=> array('name' => 'land', 'entity' => 'real estate', 'idn' => true, 'dnssec' => true),
				'lawyer'			=> array('name' => 'lawyer', 'entity' => 'lawyers and legal organizations', 'idn' => null, 'dnssec' => true),
				'lease'				=> array('name' => 'lease', 'entity' => 'financing', 'idn' => true, 'dnssec' => true),
				'legal'				=> array('name' => 'legal', 'entity' => 'lawyers and legal organizations', 'idn' => true, 'dnssec' => true),
				'lgbt'				=> array('name' => 'lgbt', 'entity' => 'the lesbian, gay, bisexual and transgender community', 'idn' => null, 'dnssec' => true),
				'life'				=> array('name' => 'life', 'entity' => 'general', 'idn' => true, 'dnssec' => true),
				'lighting'			=> array('name' => 'lighting', 'entity' => 'lighting', 'idn' => true, 'dnssec' => true),
				'limited'			=> array('name' => 'limited', 'entity' => 'general', 'idn' => true, 'dnssec' => true),
				'limo'				=> array('name' => 'limo', 'entity' => 'limousine businesses', 'idn' => true, 'dnssec' => true),
				'link'				=> array('name' => 'link', 'entity' => 'connecting to information', 'idn' => true, 'dnssec' => true),
				'loan'				=> array('name' => 'loan', 'entity' => 'banks and lenders', 'idn' => null, 'dnssec' => true),
				'loans'				=> array('name' => 'loans', 'entity' => 'banks and lenders', 'idn' => true, 'dnssec' => true),
				'lol'				=> array('name' => 'lol', 'entity' => 'LOL: laughing out loud', 'idn' => null, 'dnssec' => true),
				'lotto'				=> array('name' => 'lotto', 'entity' => 'lotto', 'idn' => null, 'dnssec' => true),
				'love'				=> array('name' => 'love', 'entity' => 'dating sites', 'idn' => null, 'dnssec' => true),
				'luxe'				=> array('name' => 'luxe', 'entity' => 'luxe', 'idn' => null, 'dnssec' => true),
				'luxury'			=> array('name' => 'luxury', 'entity' => 'businesses catering to the wealthy', 'idn' => true, 'dnssec' => true),
				'management'		=> array('name' => 'management', 'entity' => 'business management', 'idn' => true, 'dnssec' => true),
				'market'			=> array('name' => 'market', 'entity' => 'marketing services and retailers', 'idn' => null, 'dnssec' => true),
				'marketing'			=> array('name' => 'marketing', 'entity' => 'marketing services', 'idn' => true, 'dnssec' => true),
				'markets'			=> array('name' => 'markets', 'entity' => 'financial and stock markets', 'idn' => null, 'dnssec' => true),
				'mba'				=> array('name' => 'mba', 'entity' => '経営学修士', 'idn' => true, 'dnssec' => true),
				'media'				=> array('name' => 'media', 'entity' => 'general media interests', 'idn' => true, 'dnssec' => true),
				'meet'				=> array('name' => 'meet', 'entity' => 'social gatherings, meeting new people', 'idn' => null, 'dnssec' => true),
				'meme'				=> array('name' => 'meme', 'entity' => 'インターネットミーム', 'idn' => null, 'dnssec' => true),
				'memorial'			=> array('name' => 'memorial', 'entity' => 'memorial sites', 'idn' => true, 'dnssec' => true),
				'men'				=> array('name' => 'men', 'entity' => '男性', 'idn' => null, 'dnssec' => true),
				'menu'				=> array('name' => 'menu', 'entity' => 'レストラン', 'idn' => true, 'dnssec' => true),
				'mobi'				=> array('name' => 'mobi', 'entity' => 'モバイル端末', 'idn' => true, 'dnssec' => false),
				'moe'				=> array('name' => 'moe', 'entity' => '萌え', 'idn' => true, 'dnssec' => true),
				'money'				=> array('name' => 'money', 'entity' => '金融', 'idn' => true, 'dnssec' => true),
				'mortgage'			=> array('name' => 'mortgage', 'entity' => 'mortgage lenders', 'idn' => null, 'dnssec' => true),
				'motorcycles'		=> array('name' => 'motorcycles', 'entity' => 'motorcycles', 'idn' => null, 'dnssec' => true),
				'mov'				=> array('name' => 'mov', 'entity' => 'デジタル動画', 'idn' => null, 'dnssec' => true),
				'movie'				=> array('name' => 'movie', 'entity' => 'movies and cinemas', 'idn' => true, 'dnssec' => true),
				'museum'			=> array('name' => 'museum', 'entity' => 'museums', 'idn' => true, 'dnssec' => true),
				'name'				=> array('name' => 'name', 'entity' => 'individuals, by name', 'idn' => true, 'dnssec' => true),
				'navy'				=> array('name' => 'navy', 'entity' => 'defense contractors', 'idn' => null, 'dnssec' => true),
				'network'			=> array('name' => 'network', 'entity' => 'general', 'idn' => true, 'dnssec' => true),
				'new'				=> array('name' => 'new', 'entity' => 'general', 'idn' => null, 'dnssec' => true),
				'news'				=> array('name' => 'news', 'entity' => 'news sites', 'idn' => null, 'dnssec' => true),
				'ngo'				=> array('name' => 'ngo', 'entity' => '非政府組織', 'idn' => null, 'dnssec' => true),
				'ninja'				=> array('name' => 'ninja', 'entity' => 'general expertise', 'idn' => true, 'dnssec' => true),
				'one'				=> array('name' => 'one', 'entity' => 'generic', 'idn' => null, 'dnssec' => true),
				'ong'				=> array('name' => 'ong', 'entity' => '非政府組織', 'idn' => null, 'dnssec' => true),
				'onl'				=> array('name' => 'onl', 'entity' => 'online', 'idn' => null, 'dnssec' => true),
				'online'			=> array('name' => 'online', 'entity' => 'generic', 'idn' => null, 'dnssec' => true),
				'ooo'				=> array('name' => 'ooo', 'entity' => 'general', 'idn' => false, 'dnssec' => true),
				'organic'			=> array('name' => 'organic', 'entity' => 'organic', 'idn' => null, 'dnssec' => true),
				'partners'			=> array('name' => 'partners', 'entity' => 'businesses', 'idn' => true, 'dnssec' => true),
				'parts'				=> array('name' => 'parts', 'entity' => 'manufacturing and consumer auto', 'idn' => true, 'dnssec' => true),
				'party'				=> array('name' => 'party', 'entity' => 'nightclubs and social gatherings', 'idn' => null, 'dnssec' => true),
				'pharmacy'			=> array('name' => 'pharmacy', 'entity' => 'pharmacies', 'idn' => null, 'dnssec' => true),
				'photo'				=> array('name' => 'photo', 'entity' => 'photography and photo-sharing', 'idn' => true, 'dnssec' => true),
				'photography'		=> array('name' => 'photography', 'entity' => 'photography and photo-sharing', 'idn' => true, 'dnssec' => true),
				'photos'			=> array('name' => 'photos', 'entity' => 'photography and photo-sharing', 'idn' => true, 'dnssec' => true),
				'physio'			=> array('name' => 'physio', 'entity' => 'physical therapists', 'idn' => null, 'dnssec' => true),
				'pics'				=> array('name' => 'pics', 'entity' => 'photography and photo-sharing', 'idn' => true, 'dnssec' => true),
				'pictures'			=> array('name' => 'pictures', 'entity' => 'photography and photo-sharing', 'idn' => true, 'dnssec' => true),
				'feedback'			=> array('name' => 'feedback', 'entity' => 'feedback', 'idn' => null, 'dnssec' => true),
				'pink'				=> array('name' => 'pink', 'entity' => 'those who like the color pink', 'idn' => true, 'dnssec' => true),
				'pizza'				=> array('name' => 'pizza', 'entity' => 'pizza parlors', 'idn' => true, 'dnssec' => true),
				'place'				=> array('name' => 'place', 'entity' => 'general', 'idn' => true, 'dnssec' => true),
				'plumbing'			=> array('name' => 'plumbing', 'entity' => 'plumbing businesses', 'idn' => true, 'dnssec' => true),
				'plus'				=> array('name' => 'plus', 'entity' => 'generic', 'idn' => true, 'dnssec' => true),
				'poker'				=> array('name' => 'poker', 'entity' => 'ポーカー', 'idn' => null, 'dnssec' => true),
				'porn'				=> array('name' => 'porn', 'entity' => 'adult entertainment', 'idn' => true, 'dnssec' => true),
				'post'				=> array('name' => 'post', 'entity' => 'postal services', 'idn' => false, 'dnssec' => true),
				'press'				=> array('name' => 'press', 'entity' => 'publishing and journalism', 'idn' => null, 'dnssec' => true),
				'pro'				=> array('name' => 'pro', 'entity' => 'professions', 'idn' => false, 'dnssec' => false),
				'productions'		=> array('name' => 'productions', 'entity' => 'studio/art businesses', 'idn' => true, 'dnssec' => true),
				'prof'				=> array('name' => 'prof', 'entity' => 'Professors, teachers and learning', 'idn' => null, 'dnssec' => true),
				'properties'		=> array('name' => 'properties', 'entity' => 'real estate', 'idn' => true, 'dnssec' => true),
				'property'			=> array('name' => 'property', 'entity' => 'real estate', 'idn' => true, 'dnssec' => true),
				'qpon'				=> array('name' => 'qpon', 'entity' => 'coupons', 'idn' => null, 'dnssec' => true),
				'racing'			=> array('name' => 'racing', 'entity' => 'racing', 'idn' => null, 'dnssec' => true),
				'recipes'			=> array('name' => 'recipes', 'entity' => 'recipes and cooking', 'idn' => true, 'dnssec' => true),
				'red'				=> array('name' => 'red', 'entity' => 'those who like the color red', 'idn' => true, 'dnssec' => true),
				'rehab'				=> array('name' => 'rehab', 'entity' => 'リハビリテーションセンター and support sites', 'idn' => null, 'dnssec' => true),
				'ren'				=> array('name' => 'ren', 'entity' => '人人網ユーザー', 'idn' => null, 'dnssec' => true),
				'rent'				=> array('name' => 'rent', 'entity' => 'Real estate professionals and small businesses', 'idn' => null, 'dnssec' => true),
				'rentals'			=> array('name' => 'rentals', 'entity' => 'short-term ownership', 'idn' => true, 'dnssec' => true),
				'repair'			=> array('name' => 'repair', 'entity' => 'general repair/maintenance businesses', 'idn' => true, 'dnssec' => true),
				'report'			=> array('name' => 'report', 'entity' => 'business services', 'idn' => true, 'dnssec' => true),
				'republican'		=> array('name' => 'republican', 'entity' => '共和党 politics', 'idn' => null, 'dnssec' => true),
				'rest'				=> array('name' => 'rest', 'entity' => 'Restaurants and related industry', 'idn' => true, 'dnssec' => true),
				'review'			=> array('name' => 'review', 'entity' => 'public reviews', 'idn' => null, 'dnssec' => true),
				'reviews'			=> array('name' => 'reviews', 'entity' => 'public reviews', 'idn' => true, 'dnssec' => true),
				'rich'				=> array('name' => 'rich', 'entity' => 'businesses catering to the wealthy', 'idn' => null, 'dnssec' => true),
				'rip'				=> array('name' => 'rip', 'entity' => 'memorial sites', 'idn' => null, 'dnssec' => true),
				'rocks'				=> array('name' => 'rocks', 'entity' => 'general', 'idn' => true, 'dnssec' => true),
				'rodeo'				=> array('name' => 'rodeo', 'entity' => 'ロデオ interest', 'idn' => true, 'dnssec' => true),
				'rsvp'				=> array('name' => 'rsvp', 'entity' => 'Invitations and replies', 'idn' => null, 'dnssec' => true),
				'run'				=> array('name' => 'run', 'entity' => 'running and jogging', 'idn' => true, 'dnssec' => true),
				'sale'				=> array('name' => 'sale', 'entity' => 'retail', 'idn' => null, 'dnssec' => true),
				'school'			=> array('name' => 'school', 'entity' => 'schools', 'idn' => true, 'dnssec' => true),
				'science'			=> array('name' => 'science', 'entity' => 'science-related sites', 'idn' => null, 'dnssec' => true),
				'services'			=> array('name' => 'services', 'entity' => 'business services', 'idn' => true, 'dnssec' => true),
				'sex'				=> array('name' => 'sex', 'entity' => 'adult entertainment (pornography)', 'idn' => true, 'dnssec' => true),
				'sexy'				=> array('name' => 'sexy', 'entity' => 'adult entertainment', 'idn' => true, 'dnssec' => true),
				'shoes'				=> array('name' => 'shoes', 'entity' => 'shoes', 'idn' => true, 'dnssec' => true),
				'show'				=> array('name' => 'show', 'entity' => 'entertainment and vlogs', 'idn' => true, 'dnssec' => true),
				'singles'			=> array('name' => 'singles', 'entity' => 'online dating', 'idn' => true, 'dnssec' => true),
				'site'				=> array('name' => 'site', 'entity' => 'general', 'idn' => null, 'dnssec' => true),
				'soccer'			=> array('name' => 'soccer', 'entity' => 'サッカー', 'idn' => true, 'dnssec' => true),
				'social'			=> array('name' => 'social', 'entity' => 'general interest', 'idn' => true, 'dnssec' => true),
				'software'			=> array('name' => 'software', 'entity' => 'computer software', 'idn' => null, 'dnssec' => true),
				'solar'				=> array('name' => 'solar', 'entity' => 'solar-power', 'idn' => true, 'dnssec' => true),
				'solutions'			=> array('name' => 'solutions', 'entity' => 'business services', 'idn' => true, 'dnssec' => true),
				'space'				=> array('name' => 'space', 'entity' => 'as a creative space', 'idn' => null, 'dnssec' => true),
				'studio'			=> array('name' => 'studio', 'entity' => 'art, fitness, & entertainment', 'idn' => true, 'dnssec' => true),
				'style'				=> array('name' => 'style', 'entity' => 'fashion', 'idn' => true, 'dnssec' => true),
				'sucks'				=> array('name' => 'sucks', 'entity' => 'gripe sites', 'idn' => null, 'dnssec' => true),
				'supplies'			=> array('name' => 'supplies', 'entity' => 'manufacturing industries', 'idn' => true, 'dnssec' => true),
				'supply'			=> array('name' => 'supply', 'entity' => 'manufacturing industries', 'idn' => true, 'dnssec' => true),
				'support'			=> array('name' => 'support', 'entity' => 'help pages', 'idn' => true, 'dnssec' => true),
				'surf'				=> array('name' => 'surf', 'entity' => 'surfing', 'idn' => null, 'dnssec' => true),
				'surgery'			=> array('name' => 'surgery', 'entity' => 'healthcare industry', 'idn' => true, 'dnssec' => true),
				'systems'			=> array('name' => 'systems', 'entity' => 'technology', 'idn' => true, 'dnssec' => true),
				'tattoo'			=> array('name' => 'tattoo', 'entity' => 'tattoo aficionados', 'idn' => true, 'dnssec' => true),
				'tax'				=> array('name' => 'tax', 'entity' => 'financial', 'idn' => true, 'dnssec' => true),
				'taxi'				=> array('name' => 'taxi', 'entity' => 'taxi services', 'idn' => true, 'dnssec' => true),
				'team'				=> array('name' => 'team', 'entity' => 'team sports', 'idn' => true, 'dnssec' => true),
				'technology'		=> array('name' => 'technology', 'entity' => 'technology', 'idn' => true, 'dnssec' => true),
				'tel'				=> array('name' => 'tel', 'entity' => 'Internet communication services', 'idn' => true, 'dnssec' => false),
				'tennis'			=> array('name' => 'tennis', 'entity' => 'テニス', 'idn' => true, 'dnssec' => true),
				'theater'			=> array('name' => 'theater', 'entity' => 'theaters and cinemas', 'idn' => true, 'dnssec' => true),
				'tips'				=> array('name' => 'tips', 'entity' => 'general help topics', 'idn' => true, 'dnssec' => true),
				'tires'				=> array('name' => 'tires', 'entity' => 'tire manufacturers', 'idn' => true, 'dnssec' => true),
				'today'				=> array('name' => 'today', 'entity' => 'general', 'idn' => true, 'dnssec' => true),
				'tools'				=> array('name' => 'tools', 'entity' => 'manufacturing industries', 'idn' => true, 'dnssec' => true),
				'top'				=> array('name' => 'top', 'entity' => 'general', 'idn' => null, 'dnssec' => true),
				'tours'				=> array('name' => 'tours', 'entity' => 'tourism', 'idn' => true, 'dnssec' => true),
				'town'				=> array('name' => 'town', 'entity' => 'generic geographic', 'idn' => true, 'dnssec' => true),
				'toys'				=> array('name' => 'toys', 'entity' => 'toy businesses', 'idn' => true, 'dnssec' => true),
				'trade'				=> array('name' => 'trade', 'entity' => 'businesses', 'idn' => true, 'dnssec' => true),
				'training'			=> array('name' => 'training', 'entity' => 'training and how-tos', 'idn' => true, 'dnssec' => true),
				'travel'			=> array('name' => 'travel', 'entity' => 'travel and tourism industry related sites', 'idn' => false, 'dnssec' => false),
				'university'		=> array('name' => 'university', 'entity' => 'young adults, university life', 'idn' => true, 'dnssec' => true),
				'vacations'			=> array('name' => 'vacations', 'entity' => 'travel', 'idn' => true, 'dnssec' => true),
				'vet'				=> array('name' => 'vet', 'entity' => 'veterans and veterinarians', 'idn' => true, 'dnssec' => true),
				'video'				=> array('name' => 'video', 'entity' => 'video sharing', 'idn' => null, 'dnssec' => true),
				'villas'			=> array('name' => 'villas', 'entity' => 'real estate and/or travel businesses', 'idn' => true, 'dnssec' => true),
				'vision'			=> array('name' => 'vision', 'entity' => 'eye-care businesses', 'idn' => true, 'dnssec' => true),
				'vodka'				=> array('name' => 'vodka', 'entity' => 'ウォッカ-related businesses and interest', 'idn' => true, 'dnssec' => true),
				'vote'				=> array('name' => 'vote', 'entity' => 'democratic elections and campaign websites', 'idn' => null, 'dnssec' => true),
				'voting'			=> array('name' => 'voting', 'entity' => 'polling sites', 'idn' => true, 'dnssec' => true),
				'voyage'			=> array('name' => 'voyage', 'entity' => 'travel', 'idn' => true, 'dnssec' => true),
				'wang'				=> array('name' => 'wang', 'entity' => 'general', 'idn' => true, 'dnssec' => true),
				'watch'				=> array('name' => 'watch', 'entity' => 'Watches', 'idn' => true, 'dnssec' => true),
				'webcam'			=> array('name' => 'webcam', 'entity' => 'Web cam shows and video sharing', 'idn' => true, 'dnssec' => true),
				'website'			=> array('name' => 'website', 'entity' => 'general', 'idn' => null, 'dnssec' => true),
				'wed'				=> array('name' => 'wed', 'entity' => 'engaged couples and wedding-oriented businesses', 'idn' => false, 'dnssec' => true),
				'wedding'			=> array('name' => 'wedding', 'entity' => 'wedding-oriented businesses', 'idn' => true, 'dnssec' => true),
				'whoswho'			=> array('name' => 'whoswho', 'entity' => 'general', 'idn' => true, 'dnssec' => true),
				'wiki'				=> array('name' => 'wiki', 'entity' => 'ウィキ', 'idn' => true, 'dnssec' => true),
				'win'				=> array('name' => 'win', 'entity' => 'games, Microsoft Windows', 'idn' => null, 'dnssec' => true),
				'work'				=> array('name' => 'work', 'entity' => 'general', 'idn' => true, 'dnssec' => true),
				'works'				=> array('name' => 'works', 'entity' => 'general', 'idn' => true, 'dnssec' => true),
				'world'				=> array('name' => 'world', 'entity' => 'general', 'idn' => true, 'dnssec' => true),
				'wtf'				=> array('name' => 'wtf', 'entity' => 'general', 'idn' => true, 'dnssec' => true),
				'xxx'				=> array('name' => 'xxx', 'entity' => 'adult entertainment', 'idn' => true, 'dnssec' => true),
				'xyz'				=> array('name' => 'xyz', 'entity' => 'general', 'idn' => true, 'dnssec' => true),
				'yoga'				=> array('name' => 'yoga', 'entity' => 'ヨガ', 'idn' => true, 'dnssec' => true),
				'zone'				=> array('name' => 'zone', 'entity' => 'general', 'idn' => true, 'dnssec' => true),
				'maison'			=> array('name' => 'maison', 'entity' => 'house', 'idn' => true, 'dnssec' => true),
				'abogado'			=> array('name' => 'abogado', 'entity' => 'lawyer', 'idn' => null, 'dnssec' => true),
				'gratis'			=> array('name' => 'gratis', 'entity' => 'free', 'idn' => true, 'dnssec' => true),
				'futbol'			=> array('name' => 'futbol', 'entity' => 'サッカー', 'idn' => true, 'dnssec' => true),
				'juegos'			=> array('name' => 'juegos', 'entity' => 'games', 'idn' => true, 'dnssec' => true),
				'soy'				=> array('name' => 'soy', 'entity' => '大豆', 'idn' => true, 'dnssec' => true),
				'tienda'			=> array('name' => 'tienda', 'entity' => 'shop', 'idn' => true, 'dnssec' => true),
				'uno'				=> array('name' => 'uno', 'entity' => 'ウノ', 'idn' => true, 'dnssec' => true),
				'viajes'			=> array('name' => 'viajes', 'entity' => 'travel', 'idn' => true, 'dnssec' => true),
				'haus'				=> array('name' => 'haus', 'entity' => 'house', 'idn' => true, 'dnssec' => true),
				'immobilien'		=> array('name' => 'immobilien', 'entity' => 'real estate', 'idn' => true, 'dnssec' => true),
				'jetzt'				=> array('name' => 'jetzt', 'entity' => 'now', 'idn' => true, 'dnssec' => true),
				'kaufen'			=> array('name' => 'kaufen', 'entity' => 'buy', 'idn' => true, 'dnssec' => true),
				'reise'				=> array('name' => 'reise', 'entity' => 'travel', 'idn' => true, 'dnssec' => true),
				'reisen'			=> array('name' => 'reisen', 'entity' => 'traveling', 'idn' => true, 'dnssec' => true),
				'schule'			=> array('name' => 'schule', 'entity' => 'school', 'idn' => true, 'dnssec' => true),
				'versicherung'		=> array('name' => 'versicherung', 'entity' => 'insurance', 'idn' => true, 'dnssec' => true),
				'desi'				=> array('name' => 'desi', 'entity' => '南アジアの人々や文化を指す言葉', 'idn' => null, 'dnssec' => true),
				'shiksha'			=> array('name' => 'shiksha', 'entity' => '教育', 'idn' => null, 'dnssec' => true),
				'casa'				=> array('name' => 'casa', 'entity' => '家', 'idn' => true, 'dnssec' => true),
				'cafe'				=> array('name' => 'cafe', 'entity' => 'カフェ', 'idn' => true, 'dnssec' => true),
				'immo'				=> array('name' => 'immo', 'entity' => '不動産', 'idn' => true, 'dnssec' => true),
				'moda'				=> array('name' => 'moda', 'entity' => 'ファッション', 'idn' => true, 'dnssec' => true),
				'voto'				=> array('name' => 'voto', 'entity' => '投票', 'idn' => null, 'dnssec' => true),
				'bar'				=> array('name' => 'bar', 'entity' => 'バー', 'idn' => true, 'dnssec' => true),
				'bank'				=> array('name' => 'bank', 'entity' => '銀行', 'idn' => null, 'dnssec' => true),
				'coop'				=> array('name' => 'coop', 'entity' => '協同組合', 'idn' => false, 'dnssec' => false),
				'enterprises'		=> array('name' => 'enterprises', 'entity' => 'business associations', 'idn' => true, 'dnssec' => true),
				'industries'		=> array('name' => 'industries', 'entity' => 'industrial businesses', 'idn' => true, 'dnssec' => true),
				'institute'			=> array('name' => 'institute', 'entity' => 'Established business associations', 'idn' => true, 'dnssec' => true),
				'ltda'				=> array('name' => 'ltda', 'entity' => '南アメリカの企業', 'idn' => null, 'dnssec' => true),
				'pub'				=> array('name' => 'pub', 'entity' => 'パブ', 'idn' => true, 'dnssec' => true),
				'realtor'			=> array('name' => 'realtor', 'entity' => '不動産仲買業者', 'idn' => null, 'dnssec' => true),
				'reit'				=> array('name' => 'reit', 'entity' => 'REIT', 'idn' => null, 'dnssec' => true),
				'rest'				=> array('name' => 'rest', 'entity' => 'レストラン', 'idn' => true, 'dnssec' => true),
				'restaurant'		=> array('name' => 'restaurant', 'entity' => 'レストラン', 'idn' => true, 'dnssec' => true),
				'sarl'				=> array('name' => 'sarl', 'entity' => '有限会社', 'idn' => true, 'dnssec' => true),
				'ventures'			=> array('name' => 'ventures', 'entity' => 'funding for start-ups', 'idn' => true, 'dnssec' => true),
		);
	}
}
